### ISSUE TITLE
vagrant up gives error "is_port_open.rb:21:in `initialize' ...

### ISSUE THREAD

**Issue by saubury** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#24]
Hi

When running "vagrant up" I got the error "**is_port_open.rb:21:in `initialize': ... connect(2) for "0.0.0.0" port 10008 (Errno::EADDRNOTAVAIL)**"

I got around this problem by adding '**, host_ip: "127.0.0.1"**' to all the forwarded_port lines in Vagrantfile

For example, the first line is

config.vm.network "forwarded_port", guest: 10008, host: 10008, host_ip: "127.0.0.1"

I think this is a problem with Windows 10 hosts

**Comment by andzhik** [comment]
Looks like to same issue as https://github.com/rapid7/metasploitable3/issues/106
Installing Vagrant 1.9.2 helps.
