### ISSUE TITLE
Error running the Kafka

### ISSUE THREAD

**Issue by kitgary** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#5]
The Kafka is running in Docker but when I checked the logs, there are some errors.

[2016-11-28 05:03:05,887] INFO Opening socket connection to server lambda-pluralsight/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2016-11-28 05:03:05,888] WARN Session 0x158a9476ad20001 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

What is the problem? May I ignore this problem and follow the course? Or should I reinstall the vagrant?

**Comment by aalkilani** [comment]
You can ignore those. Everything should work as expected. This is Kafka being too chatty about something it recovers from.
